// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppRH.Data;

#nullable disable

namespace WebAppRH.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428215701_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAppRH.Models.Compte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Comptes");
                });

            modelBuilder.Entity("WebAppRH.Models.DemandeConge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSoumission")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeId")
                        .HasColumnType("int");

                    b.Property<string>("MotifRefus")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ValideParId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.HasIndex("ValideParId");

                    b.ToTable("DemandesConge");
                });

            modelBuilder.Entity("WebAppRH.Models.Departement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResponsableId")
                        .IsUnique()
                        .HasFilter("[ResponsableId] IS NOT NULL");

                    b.ToTable("Departements");
                });

            modelBuilder.Entity("WebAppRH.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TypeUtilisateur")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator<string>("TypeUtilisateur").HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebAppRH.Models.Administrateur", b =>
                {
                    b.HasBaseType("WebAppRH.Models.Utilisateur");

                    b.HasDiscriminator().HasValue("Administrateur");
                });

            modelBuilder.Entity("WebAppRH.Models.Employe", b =>
                {
                    b.HasBaseType("WebAppRH.Models.Utilisateur");

                    b.Property<int?>("DepartementId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoldeConge")
                        .HasColumnType("int");

                    b.HasIndex("DepartementId");

                    b.HasIndex("ManagerId");

                    b.HasDiscriminator().HasValue("Employe");
                });

            modelBuilder.Entity("WebAppRH.Models.Manager", b =>
                {
                    b.HasBaseType("WebAppRH.Models.Utilisateur");

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("WebAppRH.Models.Compte", b =>
                {
                    b.HasOne("WebAppRH.Models.Utilisateur", "Utilisateur")
                        .WithOne("Compte")
                        .HasForeignKey("WebAppRH.Models.Compte", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("WebAppRH.Models.DemandeConge", b =>
                {
                    b.HasOne("WebAppRH.Models.Employe", "Employe")
                        .WithMany("DemandesConge")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppRH.Models.Manager", "ValidePar")
                        .WithMany("DemandesValidees")
                        .HasForeignKey("ValideParId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employe");

                    b.Navigation("ValidePar");
                });

            modelBuilder.Entity("WebAppRH.Models.Departement", b =>
                {
                    b.HasOne("WebAppRH.Models.Manager", "Responsable")
                        .WithOne("Departement")
                        .HasForeignKey("WebAppRH.Models.Departement", "ResponsableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("WebAppRH.Models.Employe", b =>
                {
                    b.HasOne("WebAppRH.Models.Departement", "Departement")
                        .WithMany("Employes")
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebAppRH.Models.Manager", "Manager")
                        .WithMany("Equipe")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departement");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("WebAppRH.Models.Departement", b =>
                {
                    b.Navigation("Employes");
                });

            modelBuilder.Entity("WebAppRH.Models.Utilisateur", b =>
                {
                    b.Navigation("Compte");
                });

            modelBuilder.Entity("WebAppRH.Models.Employe", b =>
                {
                    b.Navigation("DemandesConge");
                });

            modelBuilder.Entity("WebAppRH.Models.Manager", b =>
                {
                    b.Navigation("DemandesValidees");

                    b.Navigation("Departement");

                    b.Navigation("Equipe");
                });
#pragma warning restore 612, 618
        }
    }
}
